### ISSUE TITLE
body class

### ISSUE THREAD

**Issue by petrovicivan** [ivebe/CyrLatConverter#10]
README.md u primeru nema CyrLatConvert body class

**Comment by ivebe** [comment]
Nema, jer nije neophodna. Prvobitna verzija plugin-a je zahtevala da se dodeli neka klasa, kasnije je to ispravljeno tako da moze da stoji, ali i ne mora. Nacin na koji se sada gadja "body" je taj sto se u selektoru jQuery-a navede deo DOM-a koji je potrebno presloviti.

Na primer, ako zelimo da preslovimo celu stranu, dakle ceo body potrebno je pozvati plugin ovako `$("body").CyrLatConverter();` naravno vi i dalje mozete staviti *CyrLatConvert* u body i pozvati sa `$(".CyrLatConvert").CyrLatConverter();` ali efekat je isti.
