### ISSUE TITLE
Exclude text to be translatable

### ISSUE THREAD

**Issue by Soullighter** [ivebe/CyrLatConverter#27]
I there a way to exclude some text to be translatable?
For example, my website is all in Serbian language. but i have text FakeNews, that is obviously on English. So i don't want to translate that text at all on Cyrillic.

**Comment by ivebe** [comment]
You can find all options in here: https://ivebe.com/blog/cyrillic-to-latin-and-latin-to-cyrillic-javascript-library.html

In short you can wrap content you wish to skip with class "**CyrLatIgnore**", or if you wish you can name class you wish to be ignored from transliteration in the initialisation options (also explained in the link I sent).

**Comment by Soullighter** [comment]
Thank you for reply.
I already found it, but forgot to tell you here.
Thank you for your time that you spend creating this library.
Cheers
