### ISSUE TITLE
Roman numerals get screwed up when transliterating from latin to cyrilic

### ISSUE THREAD

**Issue by lukin155** [ivebe/CyrLatConverter#29]
When converting text like "Stefan Uroš II Milutin", you get "Стефан Урош ИИ Милутин".

**Comment by ivebe** [comment]
That's because II are literally two latin letters "I". To avoid that, you can 1) enter II in the ignore list 2) wrap text in the css ignore class. More info can be found on readme page, or in the article here https://ivebe.com/blog/cyrillic-to-latin-and-latin-to-cyrillic-javascript-library.html

**Comment by lukin155** [comment]
@ivebe explained how this can be solved.
