### ISSUE TITLE
The transliteration of щ/Щ isn't supported

### ISSUE THREAD

**Issue by petapro** [ivebe/CyrLatConverter#30]
**The transiliteration of щ/Щ isn't supported**

All cyrillic letters are transliterated very well by the the CyrLatConverter, only the letter щ (in upper case Щ) is not supported yet.

Could you add the letter to the [mapping](https://github.com/ivebe/CyrLatConverter/blob/master/src/cyrlatconverter.js#L142)?

This letter occurs e.g. in the word  _Хрущёв_ (_Khrushchev_).

**Comment by ivebe** [comment]
Russian alphabet is not supported, simple reason is I do not know the language :) Beside щ also letters from Russian alphabet are missing, if transliteration is same as in Serbian where you switch just single letters, then library could probably be upgraded. Additionally for the double letter chaining in this library, Serbian dictionary has been scanned and some general rules are added, that's one of the strengths, so I would need to do the same for the Russian language, but like I said, I don't speak the language, so it's impossibile without help from a native speaker.
