### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by arodic** [ivebe/CyrLatConverter#4]
I would like to use this project but I cant tell if the license allows that. Is it MIT? Apache 2.0? Some comments suggest this is copyrighted code. Is that correct?

> @copyright Danijel Petrovic, www.ivebe.com, 2014

**Comment by arodic** [comment]
My bad, I found Apache 2.0

**Comment by ivebe** [comment]
Hi, I'm glad you found it. If you have any questions or concerns about project or licence, feel free to contact me.

Enjoy :)
